# Site wide configuration

title:            crawford.cc
locale:           en_US
url:              http://crawford.cc


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Josh Crawford
  avatar: https://s.gravatar.com/avatar/76708b9af92b41d3861956800fc75a54?s=100
  bio: "I have a passion for small companies and start-ups that can utilize my skills as a full stack web applications developer. During my fourteen years of experience, I have worked with a wide array of clients ranging from Kraft Foods to the Department of Defense. I am a certified CrossFit instructor, wilderness survival expert and bitcoin enthusiast."
  email: josh@crawford.cc
  disqus-shortname: joshcrawford
  twitter: thejoshcrawford
  facebook:
  google:
    plus:
    analytics: 
    verify: 
    ad-client: 
    ad-slot: 
  bing-verify: 
  github: thejoshcrawford
  stackoverflow: 965935/josh-c
  linkedin: thejoshcrawford
  instagram:
  lastfm: 
  tumblr: 
  pinterest: 
  foursquare: 
  steam: 
  dribbble: 
  youtube: 
  soundcloud: 
  weibo: 
  flickr:
  resumemonk: 9644-josh/resumes/7300

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
